apiPort: 8080

server:
  port: ${apiPort}
  error:
    include-message: always

spring:
  main:
    web-application-type: reactive
  data:
    mongodb:
      uri: mongodb://localhost:27017/orderdb

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

grpc:
  server:
    port: 9090
    security:
      enabled: false

akka:
  actor:
    provider: "local"
